# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ovpn_setup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Edit_Dialog(object):
    def setupUi(self, Edit_Dialog):
        Edit_Dialog.setObjectName("Edit_Dialog")
        Edit_Dialog.resize(317, 234)
        font = QtGui.QFont()
        font.setPointSize(9)
        Edit_Dialog.setFont(font)
        self.dnsBox = QtWidgets.QComboBox(Edit_Dialog)
        self.dnsBox.setGeometry(QtCore.QRect(140, 80, 151, 22))
        self.dnsBox.setObjectName("dnsBox")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsLabel = QtWidgets.QLabel(Edit_Dialog)
        self.dnsLabel.setGeometry(QtCore.QRect(20, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dnsLabel.setFont(font)
        self.dnsLabel.setObjectName("dnsLabel")
        self.protoBox = QtWidgets.QComboBox(Edit_Dialog)
        self.protoBox.setGeometry(QtCore.QRect(140, 20, 51, 22))
        self.protoBox.setObjectName("protoBox")
        self.protoBox.addItem("")
        self.protoBox.addItem("")
        self.protoLabel = QtWidgets.QLabel(Edit_Dialog)
        self.protoLabel.setGeometry(QtCore.QRect(40, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.protoLabel.setFont(font)
        self.protoLabel.setObjectName("protoLabel")
        self.portEdit = QtWidgets.QLineEdit(Edit_Dialog)
        self.portEdit.setGeometry(QtCore.QRect(240, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portEdit.setFont(font)
        self.portEdit.setObjectName("portEdit")
        self.portLabel = QtWidgets.QLabel(Edit_Dialog)
        self.portLabel.setGeometry(QtCore.QRect(200, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.ipEdit = QtWidgets.QLineEdit(Edit_Dialog)
        self.ipEdit.setGeometry(QtCore.QRect(140, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipEdit.setFont(font)
        self.ipEdit.setText("")
        self.ipEdit.setObjectName("ipEdit")
        self.ipaddLabel = QtWidgets.QLabel(Edit_Dialog)
        self.ipaddLabel.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipaddLabel.setFont(font)
        self.ipaddLabel.setObjectName("ipaddLabel")
        self.loggingBox = QtWidgets.QCheckBox(Edit_Dialog)
        self.loggingBox.setGeometry(QtCore.QRect(80, 140, 111, 18))
        self.loggingBox.setObjectName("loggingBox")
        self.clientsBox = QtWidgets.QCheckBox(Edit_Dialog)
        self.clientsBox.setGeometry(QtCore.QRect(80, 160, 171, 18))
        self.clientsBox.setChecked(True)
        self.clientsBox.setObjectName("clientsBox")
        self.networkLabel = QtWidgets.QLabel(Edit_Dialog)
        self.networkLabel.setGeometry(QtCore.QRect(30, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.networkLabel.setFont(font)
        self.networkLabel.setObjectName("networkLabel")
        self.netipEdit = QtWidgets.QLineEdit(Edit_Dialog)
        self.netipEdit.setGeometry(QtCore.QRect(140, 110, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.netipEdit.setFont(font)
        self.netipEdit.setObjectName("netipEdit")
        self.finishButton = QtWidgets.QPushButton(Edit_Dialog)
        self.finishButton.setGeometry(QtCore.QRect(100, 190, 91, 31))
        self.finishButton.setObjectName("finishButton")

        self.retranslateUi(Edit_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Edit_Dialog)

    def retranslateUi(self, Edit_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Edit_Dialog.setWindowTitle(_translate("Edit_Dialog", "Edit server configuration"))
        self.dnsBox.setItemText(0, _translate("Edit_Dialog", "OpenNIC"))
        self.dnsBox.setItemText(1, _translate("Edit_Dialog", "Google"))
        self.dnsBox.setItemText(2, _translate("Edit_Dialog", "Yandex"))
        self.dnsLabel.setText(_translate("Edit_Dialog", "Choose DNS servers:"))
        self.protoBox.setItemText(0, _translate("Edit_Dialog", "tcp"))
        self.protoBox.setItemText(1, _translate("Edit_Dialog", "udp"))
        self.protoLabel.setText(_translate("Edit_Dialog", "Choose protocol:"))
        self.portEdit.setText(_translate("Edit_Dialog", "1194"))
        self.portLabel.setText(_translate("Edit_Dialog", "Port:"))
        self.ipaddLabel.setText(_translate("Edit_Dialog", "IP address to listen:"))
        self.loggingBox.setText(_translate("Edit_Dialog", "Dissable logging"))
        self.clientsBox.setText(_translate("Edit_Dialog", "Allow client to client"))
        self.networkLabel.setText(_translate("Edit_Dialog", "Network address:"))
        self.netipEdit.setText(_translate("Edit_Dialog", "10.8.0.0/24"))
        self.finishButton.setText(_translate("Edit_Dialog", "Proceed"))

