# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConnectWindow(object):
    def setupUi(self, ConnectWindow):
        ConnectWindow.setObjectName("ConnectWindow")
        ConnectWindow.resize(322, 187)
        ConnectWindow.setDocumentMode(False)
        ConnectWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(ConnectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(110, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnConnect.setFont(font)
        self.btnConnect.setObjectName("btnConnect")
        self.ip = QtWidgets.QLineEdit(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(100, 10, 113, 25))
        self.ip.setInputMask("")
        self.ip.setObjectName("ip")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(100, 40, 113, 25))
        self.login.setInputMask("")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(100, 70, 113, 25))
        self.password.setInputMask("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_ip = QtWidgets.QLabel(self.centralwidget)
        self.label_ip.setGeometry(QtCore.QRect(70, 10, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ip.setFont(font)
        self.label_ip.setObjectName("label_ip")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(50, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.label_pass = QtWidgets.QLabel(self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(20, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_pass.setFont(font)
        self.label_pass.setObjectName("label_pass")
        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(220, 10, 41, 25))
        self.port.setInputMask("")
        self.port.setAlignment(QtCore.Qt.AlignCenter)
        self.port.setObjectName("port")
        self.remember = QtWidgets.QCheckBox(self.centralwidget)
        self.remember.setGeometry(QtCore.QRect(80, 100, 161, 23))
        self.remember.setObjectName("remember")
        self.remember.setChecked(True)
        ConnectWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConnectWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectWindow)

    def retranslateUi(self, ConnectWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectWindow.setWindowTitle(_translate("ConnectWindow", "OpenVPN Util"))
        self.btnConnect.setText(_translate("ConnectWindow", "Connect"))
        self.login.setText(_translate("ConnectWindow", "root"))
        self.label_ip.setText(_translate("ConnectWindow", "IP:"))
        self.label_login.setText(_translate("ConnectWindow", "Login:"))
        self.label_pass.setText(_translate("ConnectWindow", "Password:"))
        self.port.setText(_translate("ConnectWindow", "22"))
        self.remember.setText(_translate("ConnectWindow", "Remember connection"))

