# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 396)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serverList = QtWidgets.QListWidget(self.centralwidget)
        self.serverList.setGeometry(QtCore.QRect(20, 40, 261, 192))
        self.serverList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.serverList.setObjectName("serverList")
        self.fromserverLabel = QtWidgets.QLabel(self.centralwidget)
        self.fromserverLabel.setGeometry(QtCore.QRect(80, 10, 151, 21))
        self.fromserverLabel.setObjectName("fromserverLabel")
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setGeometry(QtCore.QRect(440, 240, 121, 31))
        self.importButton.setObjectName("importButton")
        self.importList = QtWidgets.QListWidget(self.centralwidget)
        self.importList.setGeometry(QtCore.QRect(300, 40, 261, 192))
        self.importList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.importList.setObjectName("importList")
        item = QtWidgets.QListWidgetItem()
        self.importList.addItem(item)
        self.fromfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fromfileLabel.setGeometry(QtCore.QRect(370, 10, 131, 21))
        self.fromfileLabel.setObjectName("fromfileLabel")
        self.dwnimpButton = QtWidgets.QPushButton(self.centralwidget)
        self.dwnimpButton.setEnabled(False)
        self.dwnimpButton.setGeometry(QtCore.QRect(300, 240, 121, 31))
        self.dwnimpButton.setObjectName("dwnimpButton")
        self.dwnservButton = QtWidgets.QPushButton(self.centralwidget)
        self.dwnservButton.setGeometry(QtCore.QRect(20, 240, 121, 31))
        self.dwnservButton.setObjectName("dwnservButton")
        self.revokeButton = QtWidgets.QPushButton(self.centralwidget)
        self.revokeButton.setGeometry(QtCore.QRect(160, 240, 121, 31))
        self.revokeButton.setObjectName("revokeButton")
        self.connectedText = QtWidgets.QLabel(self.centralwidget)
        self.connectedText.setGeometry(QtCore.QRect(20, 290, 91, 21))
        self.connectedText.setObjectName("connectedText")
        self.connLabel = QtWidgets.QLabel(self.centralwidget)
        self.connLabel.setGeometry(QtCore.QRect(110, 290, 91, 21))
        self.connLabel.setObjectName("connLabel")
        self.tunText = QtWidgets.QLabel(self.centralwidget)
        self.tunText.setGeometry(QtCore.QRect(20, 310, 111, 21))
        self.tunText.setObjectName("tunText")
        self.tunLabel = QtWidgets.QLabel(self.centralwidget)
        self.tunLabel.setGeometry(QtCore.QRect(130, 310, 111, 21))
        self.tunLabel.setObjectName("tunLabel")
        self.tunText_3 = QtWidgets.QLabel(self.centralwidget)
        self.tunText_3.setGeometry(QtCore.QRect(20, 330, 111, 21))
        self.tunText_3.setObjectName("tunText_3")
        self.verLabel = QtWidgets.QLabel(self.centralwidget)
        self.verLabel.setGeometry(QtCore.QRect(130, 330, 61, 21))
        self.verLabel.setObjectName("verLabel")
        self.tunText_4 = QtWidgets.QLabel(self.centralwidget)
        self.tunText_4.setGeometry(QtCore.QRect(20, 350, 131, 21))
        self.tunText_4.setObjectName("tunText_4")
        self.usersLabel = QtWidgets.QLabel(self.centralwidget)
        self.usersLabel.setGeometry(QtCore.QRect(150, 350, 61, 21))
        self.usersLabel.setObjectName("usersLabel")
        self.importButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.importButton_2.setGeometry(QtCore.QRect(440, 280, 121, 31))
        self.importButton_2.setObjectName("importButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenVPN Assitant"))
        self.fromserverLabel.setText(_translate("MainWindow", "Select user(s) from server:"))
        self.importButton.setText(_translate("MainWindow", "Import from file"))
        __sortingEnabled = self.importList.isSortingEnabled()
        self.importList.setSortingEnabled(False)
        item = self.importList.item(0)
        item.setText(_translate("MainWindow", "Import users from file"))
        self.importList.setSortingEnabled(__sortingEnabled)
        self.fromfileLabel.setText(_translate("MainWindow", "Select user(s) from file:"))
        self.dwnimpButton.setText(_translate("MainWindow", "Download imported"))
        self.dwnservButton.setText(_translate("MainWindow", "Download Selected"))
        self.revokeButton.setText(_translate("MainWindow", "Revoke Selected"))
        self.connectedText.setText(_translate("MainWindow", "Connected to:"))
        self.connLabel.setText(_translate("MainWindow", "error"))
        self.tunText.setText(_translate("MainWindow", "Current tunnel IP:"))
        self.tunLabel.setText(_translate("MainWindow", "error"))
        self.tunText_3.setText(_translate("MainWindow", "OpenVPN version:"))
        self.verLabel.setText(_translate("MainWindow", "error"))
        self.tunText_4.setText(_translate("MainWindow", "Total users on server:"))
        self.usersLabel.setText(_translate("MainWindow", "error"))
        self.importButton_2.setText(_translate("MainWindow", "Edit server config"))

