# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ovpn_setup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setup_Dialog(object):
    def setupUi(self, Setup_Dialog):
        Setup_Dialog.setObjectName("Setup_Dialog")
        Setup_Dialog.resize(317, 345)
        font = QtGui.QFont()
        font.setPointSize(9)
        Setup_Dialog.setFont(font)
        self.dnsBox = QtWidgets.QComboBox(Setup_Dialog)
        self.dnsBox.setGeometry(QtCore.QRect(140, 80, 151, 22))
        self.dnsBox.setObjectName("dnsBox")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsLabel = QtWidgets.QLabel(Setup_Dialog)
        self.dnsLabel.setGeometry(QtCore.QRect(20, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dnsLabel.setFont(font)
        self.dnsLabel.setObjectName("dnsLabel")
        self.protoBox = QtWidgets.QComboBox(Setup_Dialog)
        self.protoBox.setGeometry(QtCore.QRect(140, 20, 51, 22))
        self.protoBox.setObjectName("protoBox")
        self.protoBox.addItem("")
        self.protoBox.addItem("")
        self.protoLabel = QtWidgets.QLabel(Setup_Dialog)
        self.protoLabel.setGeometry(QtCore.QRect(40, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.protoLabel.setFont(font)
        self.protoLabel.setObjectName("protoLabel")
        self.portEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.portEdit.setGeometry(QtCore.QRect(240, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portEdit.setFont(font)
        self.portEdit.setObjectName("portEdit")
        self.portLabel = QtWidgets.QLabel(Setup_Dialog)
        self.portLabel.setGeometry(QtCore.QRect(200, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.ipEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.ipEdit.setGeometry(QtCore.QRect(140, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipEdit.setFont(font)
        self.ipEdit.setText("")
        self.ipEdit.setObjectName("ipEdit")
        self.ipaddLabel = QtWidgets.QLabel(Setup_Dialog)
        self.ipaddLabel.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipaddLabel.setFont(font)
        self.ipaddLabel.setObjectName("ipaddLabel")
        self.loggingBox = QtWidgets.QCheckBox(Setup_Dialog)
        self.loggingBox.setGeometry(QtCore.QRect(90, 240, 111, 18))
        self.loggingBox.setObjectName("loggingBox")
        self.clientsBox = QtWidgets.QCheckBox(Setup_Dialog)
        self.clientsBox.setGeometry(QtCore.QRect(90, 260, 171, 18))
        self.clientsBox.setChecked(True)
        self.clientsBox.setObjectName("clientsBox")
        self.networkLabel = QtWidgets.QLabel(Setup_Dialog)
        self.networkLabel.setGeometry(QtCore.QRect(30, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.networkLabel.setFont(font)
        self.networkLabel.setObjectName("networkLabel")
        self.netipEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.netipEdit.setGeometry(QtCore.QRect(140, 110, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.netipEdit.setFont(font)
        self.netipEdit.setObjectName("netipEdit")
        self.finishButton = QtWidgets.QPushButton(Setup_Dialog)
        self.finishButton.setGeometry(QtCore.QRect(110, 290, 91, 31))
        self.finishButton.setObjectName("finishButton")
        self.countryEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.countryEdit.setGeometry(QtCore.QRect(60, 140, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.countryEdit.setFont(font)
        self.countryEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.countryEdit.setObjectName("countryEdit")
        self.countryLabel = QtWidgets.QLabel(Setup_Dialog)
        self.countryLabel.setGeometry(QtCore.QRect(10, 140, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.countryLabel.setFont(font)
        self.countryLabel.setObjectName("countryLabel")
        self.provinceLabel = QtWidgets.QLabel(Setup_Dialog)
        self.provinceLabel.setGeometry(QtCore.QRect(100, 140, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.provinceLabel.setFont(font)
        self.provinceLabel.setObjectName("provinceLabel")
        self.provinceEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.provinceEdit.setGeometry(QtCore.QRect(160, 140, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.provinceEdit.setFont(font)
        self.provinceEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.provinceEdit.setObjectName("provinceEdit")
        self.cityLabel = QtWidgets.QLabel(Setup_Dialog)
        self.cityLabel.setGeometry(QtCore.QRect(200, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cityLabel.setFont(font)
        self.cityLabel.setObjectName("cityLabel")
        self.cityEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.cityEdit.setGeometry(QtCore.QRect(230, 140, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cityEdit.setFont(font)
        self.cityEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cityEdit.setObjectName("cityEdit")
        self.orgLabel = QtWidgets.QLabel(Setup_Dialog)
        self.orgLabel.setGeometry(QtCore.QRect(50, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.orgLabel.setFont(font)
        self.orgLabel.setObjectName("orgLabel")
        self.orgEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.orgEdit.setGeometry(QtCore.QRect(130, 170, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.orgEdit.setFont(font)
        self.orgEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.orgEdit.setObjectName("orgEdit")
        self.emailLabel = QtWidgets.QLabel(Setup_Dialog)
        self.emailLabel.setGeometry(QtCore.QRect(80, 200, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.emailEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.emailEdit.setGeometry(QtCore.QRect(130, 200, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.emailEdit.setFont(font)
        self.emailEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.emailEdit.setObjectName("emailEdit")

        self.retranslateUi(Setup_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Setup_Dialog)

    def retranslateUi(self, Setup_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Setup_Dialog.setWindowTitle(_translate("Setup_Dialog", "OpenVPN Setup"))
        self.dnsBox.setItemText(0, _translate("Setup_Dialog", "OpenNIC"))
        self.dnsBox.setItemText(1, _translate("Setup_Dialog", "Google"))
        self.dnsBox.setItemText(2, _translate("Setup_Dialog", "Yandex"))
        self.dnsLabel.setText(_translate("Setup_Dialog", "Choose DNS servers:"))
        self.protoBox.setItemText(0, _translate("Setup_Dialog", "tcp"))
        self.protoBox.setItemText(1, _translate("Setup_Dialog", "udp"))
        self.protoLabel.setText(_translate("Setup_Dialog", "Choose protocol:"))
        self.portEdit.setText(_translate("Setup_Dialog", "1194"))
        self.portLabel.setText(_translate("Setup_Dialog", "Port:"))
        self.ipaddLabel.setText(_translate("Setup_Dialog", "IP address to listen:"))
        self.loggingBox.setText(_translate("Setup_Dialog", "Dissable logging"))
        self.clientsBox.setText(_translate("Setup_Dialog", "Allow client to client"))
        self.networkLabel.setText(_translate("Setup_Dialog", "Network address:"))
        self.netipEdit.setText(_translate("Setup_Dialog", "10.8.0.0/24"))
        self.finishButton.setText(_translate("Setup_Dialog", "Proceed"))
        self.countryEdit.setText(_translate("Setup_Dialog", "RU"))
        self.countryLabel.setText(_translate("Setup_Dialog", "Country:"))
        self.provinceLabel.setText(_translate("Setup_Dialog", "Province:"))
        self.provinceEdit.setText(_translate("Setup_Dialog", "SM"))
        self.cityLabel.setText(_translate("Setup_Dialog", "City:"))
        self.cityEdit.setText(_translate("Setup_Dialog", "Smolensk"))
        self.orgLabel.setText(_translate("Setup_Dialog", "Organization:"))
        self.orgEdit.setText(_translate("Setup_Dialog", "MyOrganization"))
        self.emailLabel.setText(_translate("Setup_Dialog", "E-Mail:"))
        self.emailEdit.setText(_translate("Setup_Dialog", "me@organization.com"))

