#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


# --- Edit Design ---
class Ui_Edit_Dialog(object):
    def setupUi(self, Edit_Dialog):
        Edit_Dialog.setObjectName("Edit_Dialog")
        Edit_Dialog.resize(317, 234)
        font = QtGui.QFont()
        font.setPointSize(9)
        Edit_Dialog.setFont(font)
        self.dnsBox = QtWidgets.QComboBox(Edit_Dialog)
        self.dnsBox.setGeometry(QtCore.QRect(140, 80, 151, 22))
        self.dnsBox.setObjectName("dnsBox")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsLabel = QtWidgets.QLabel(Edit_Dialog)
        self.dnsLabel.setGeometry(QtCore.QRect(20, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dnsLabel.setFont(font)
        self.dnsLabel.setObjectName("dnsLabel")
        self.protoBox = QtWidgets.QComboBox(Edit_Dialog)
        self.protoBox.setGeometry(QtCore.QRect(140, 20, 51, 22))
        self.protoBox.setObjectName("protoBox")
        self.protoBox.addItem("")
        self.protoBox.addItem("")
        self.protoLabel = QtWidgets.QLabel(Edit_Dialog)
        self.protoLabel.setGeometry(QtCore.QRect(40, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.protoLabel.setFont(font)
        self.protoLabel.setObjectName("protoLabel")
        self.portEdit = QtWidgets.QLineEdit(Edit_Dialog)
        self.portEdit.setGeometry(QtCore.QRect(240, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portEdit.setFont(font)
        self.portEdit.setObjectName("portEdit")
        self.portLabel = QtWidgets.QLabel(Edit_Dialog)
        self.portLabel.setGeometry(QtCore.QRect(200, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.ipEdit = QtWidgets.QLineEdit(Edit_Dialog)
        self.ipEdit.setGeometry(QtCore.QRect(140, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipEdit.setFont(font)
        self.ipEdit.setText("")
        self.ipEdit.setObjectName("ipEdit")
        self.ipaddLabel = QtWidgets.QLabel(Edit_Dialog)
        self.ipaddLabel.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipaddLabel.setFont(font)
        self.ipaddLabel.setObjectName("ipaddLabel")
        self.loggingBox = QtWidgets.QCheckBox(Edit_Dialog)
        self.loggingBox.setGeometry(QtCore.QRect(80, 140, 111, 18))
        self.loggingBox.setObjectName("loggingBox")
        self.clientsBox = QtWidgets.QCheckBox(Edit_Dialog)
        self.clientsBox.setGeometry(QtCore.QRect(80, 160, 171, 18))
        self.clientsBox.setChecked(True)
        self.clientsBox.setObjectName("clientsBox")
        self.networkLabel = QtWidgets.QLabel(Edit_Dialog)
        self.networkLabel.setGeometry(QtCore.QRect(30, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.networkLabel.setFont(font)
        self.networkLabel.setObjectName("networkLabel")
        self.netipEdit = QtWidgets.QLineEdit(Edit_Dialog)
        self.netipEdit.setGeometry(QtCore.QRect(140, 110, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.netipEdit.setFont(font)
        self.netipEdit.setObjectName("netipEdit")
        self.finishButton = QtWidgets.QPushButton(Edit_Dialog)
        self.finishButton.setGeometry(QtCore.QRect(100, 190, 91, 31))
        self.finishButton.setObjectName("finishButton")

        self.retranslateUi(Edit_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Edit_Dialog)

    def retranslateUi(self, Edit_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Edit_Dialog.setWindowTitle(_translate(
            "Edit_Dialog", "Edit server configuration"))
        self.dnsBox.setItemText(0, _translate("Edit_Dialog", "OpenNIC"))
        self.dnsBox.setItemText(1, _translate("Edit_Dialog", "Google"))
        self.dnsBox.setItemText(2, _translate("Edit_Dialog", "Yandex"))
        self.dnsLabel.setText(_translate("Edit_Dialog", "Choose DNS servers:"))
        self.protoBox.setItemText(0, _translate("Edit_Dialog", "tcp"))
        self.protoBox.setItemText(1, _translate("Edit_Dialog", "udp"))
        self.protoLabel.setText(_translate("Edit_Dialog", "Choose protocol:"))
        self.portEdit.setText(_translate("Edit_Dialog", "1194"))
        self.portLabel.setText(_translate("Edit_Dialog", "Port:"))
        self.ipaddLabel.setText(_translate(
            "Edit_Dialog", "IP address to listen:"))
        self.loggingBox.setText(_translate("Edit_Dialog", "Dissable logging"))
        self.clientsBox.setText(_translate(
            "Edit_Dialog", "Allow client to client"))
        self.networkLabel.setText(_translate(
            "Edit_Dialog", "Network address:"))
        self.netipEdit.setText(_translate("Edit_Dialog", "10.8.0.0/24"))
        self.finishButton.setText(_translate("Edit_Dialog", "Proceed"))


# --- Setup Design ---
class Ui_Setup_Dialog(object):
    def setupUi(self, Setup_Dialog):
        Setup_Dialog.setObjectName("Setup_Dialog")
        Setup_Dialog.resize(317, 345)
        font = QtGui.QFont()
        font.setPointSize(9)
        Setup_Dialog.setFont(font)
        self.dnsBox = QtWidgets.QComboBox(Setup_Dialog)
        self.dnsBox.setGeometry(QtCore.QRect(140, 80, 151, 22))
        self.dnsBox.setObjectName("dnsBox")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsBox.addItem("")
        self.dnsLabel = QtWidgets.QLabel(Setup_Dialog)
        self.dnsLabel.setGeometry(QtCore.QRect(20, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dnsLabel.setFont(font)
        self.dnsLabel.setObjectName("dnsLabel")
        self.protoBox = QtWidgets.QComboBox(Setup_Dialog)
        self.protoBox.setGeometry(QtCore.QRect(140, 20, 51, 22))
        self.protoBox.setObjectName("protoBox")
        self.protoBox.addItem("")
        self.protoBox.addItem("")
        self.protoLabel = QtWidgets.QLabel(Setup_Dialog)
        self.protoLabel.setGeometry(QtCore.QRect(40, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.protoLabel.setFont(font)
        self.protoLabel.setObjectName("protoLabel")
        self.portEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.portEdit.setGeometry(QtCore.QRect(240, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portEdit.setFont(font)
        self.portEdit.setObjectName("portEdit")
        self.portLabel = QtWidgets.QLabel(Setup_Dialog)
        self.portLabel.setGeometry(QtCore.QRect(200, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.ipEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.ipEdit.setGeometry(QtCore.QRect(140, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipEdit.setFont(font)
        self.ipEdit.setText("")
        self.ipEdit.setObjectName("ipEdit")
        self.ipaddLabel = QtWidgets.QLabel(Setup_Dialog)
        self.ipaddLabel.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipaddLabel.setFont(font)
        self.ipaddLabel.setObjectName("ipaddLabel")
        self.loggingBox = QtWidgets.QCheckBox(Setup_Dialog)
        self.loggingBox.setGeometry(QtCore.QRect(90, 240, 111, 18))
        self.loggingBox.setObjectName("loggingBox")
        self.clientsBox = QtWidgets.QCheckBox(Setup_Dialog)
        self.clientsBox.setGeometry(QtCore.QRect(90, 260, 171, 18))
        self.clientsBox.setChecked(True)
        self.clientsBox.setObjectName("clientsBox")
        self.networkLabel = QtWidgets.QLabel(Setup_Dialog)
        self.networkLabel.setGeometry(QtCore.QRect(30, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.networkLabel.setFont(font)
        self.networkLabel.setObjectName("networkLabel")
        self.netipEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.netipEdit.setGeometry(QtCore.QRect(140, 110, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.netipEdit.setFont(font)
        self.netipEdit.setObjectName("netipEdit")
        self.finishButton = QtWidgets.QPushButton(Setup_Dialog)
        self.finishButton.setGeometry(QtCore.QRect(110, 290, 91, 31))
        self.finishButton.setObjectName("finishButton")
        self.countryEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.countryEdit.setGeometry(QtCore.QRect(60, 140, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.countryEdit.setFont(font)
        self.countryEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.countryEdit.setObjectName("countryEdit")
        self.countryLabel = QtWidgets.QLabel(Setup_Dialog)
        self.countryLabel.setGeometry(QtCore.QRect(10, 140, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.countryLabel.setFont(font)
        self.countryLabel.setObjectName("countryLabel")
        self.provinceLabel = QtWidgets.QLabel(Setup_Dialog)
        self.provinceLabel.setGeometry(QtCore.QRect(100, 140, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.provinceLabel.setFont(font)
        self.provinceLabel.setObjectName("provinceLabel")
        self.provinceEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.provinceEdit.setGeometry(QtCore.QRect(160, 140, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.provinceEdit.setFont(font)
        self.provinceEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.provinceEdit.setObjectName("provinceEdit")
        self.cityLabel = QtWidgets.QLabel(Setup_Dialog)
        self.cityLabel.setGeometry(QtCore.QRect(200, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cityLabel.setFont(font)
        self.cityLabel.setObjectName("cityLabel")
        self.cityEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.cityEdit.setGeometry(QtCore.QRect(230, 140, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cityEdit.setFont(font)
        self.cityEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cityEdit.setObjectName("cityEdit")
        self.orgLabel = QtWidgets.QLabel(Setup_Dialog)
        self.orgLabel.setGeometry(QtCore.QRect(50, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.orgLabel.setFont(font)
        self.orgLabel.setObjectName("orgLabel")
        self.orgEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.orgEdit.setGeometry(QtCore.QRect(130, 170, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.orgEdit.setFont(font)
        self.orgEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.orgEdit.setObjectName("orgEdit")
        self.emailLabel = QtWidgets.QLabel(Setup_Dialog)
        self.emailLabel.setGeometry(QtCore.QRect(80, 200, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.emailEdit = QtWidgets.QLineEdit(Setup_Dialog)
        self.emailEdit.setGeometry(QtCore.QRect(130, 200, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.emailEdit.setFont(font)
        self.emailEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.emailEdit.setObjectName("emailEdit")

        self.retranslateUi(Setup_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Setup_Dialog)

    def retranslateUi(self, Setup_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Setup_Dialog.setWindowTitle(
            _translate("Setup_Dialog", "OpenVPN Setup"))
        self.dnsBox.setItemText(0, _translate("Setup_Dialog", "OpenNIC"))
        self.dnsBox.setItemText(1, _translate("Setup_Dialog", "Google"))
        self.dnsBox.setItemText(2, _translate("Setup_Dialog", "Yandex"))
        self.dnsLabel.setText(_translate(
            "Setup_Dialog", "Choose DNS servers:"))
        self.protoBox.setItemText(0, _translate("Setup_Dialog", "tcp"))
        self.protoBox.setItemText(1, _translate("Setup_Dialog", "udp"))
        self.protoLabel.setText(_translate("Setup_Dialog", "Choose protocol:"))
        self.portEdit.setText(_translate("Setup_Dialog", "1194"))
        self.portLabel.setText(_translate("Setup_Dialog", "Port:"))
        self.ipaddLabel.setText(_translate(
            "Setup_Dialog", "IP address to listen:"))
        self.loggingBox.setText(_translate("Setup_Dialog", "Dissable logging"))
        self.clientsBox.setText(_translate(
            "Setup_Dialog", "Allow client to client"))
        self.networkLabel.setText(_translate(
            "Setup_Dialog", "Network address:"))
        self.netipEdit.setText(_translate("Setup_Dialog", "10.8.0.0/24"))
        self.finishButton.setText(_translate("Setup_Dialog", "Proceed"))
        self.countryEdit.setText(_translate("Setup_Dialog", "RU"))
        self.countryLabel.setText(_translate("Setup_Dialog", "Country:"))
        self.provinceLabel.setText(_translate("Setup_Dialog", "Province:"))
        self.provinceEdit.setText(_translate("Setup_Dialog", "SM"))
        self.cityLabel.setText(_translate("Setup_Dialog", "City:"))
        self.cityEdit.setText(_translate("Setup_Dialog", "Smolensk"))
        self.orgLabel.setText(_translate("Setup_Dialog", "Organization:"))
        self.orgEdit.setText(_translate("Setup_Dialog", "MyOrganization"))
        self.emailLabel.setText(_translate("Setup_Dialog", "E-Mail:"))
        self.emailEdit.setText(_translate(
            "Setup_Dialog", "me@organization.com"))


# --- Login Design ---
class Ui_ConnectWindow(object):
    def setupUi(self, ConnectWindow):
        ConnectWindow.setObjectName("ConnectWindow")
        ConnectWindow.resize(322, 187)
        ConnectWindow.setDocumentMode(False)
        ConnectWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(ConnectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(110, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnConnect.setFont(font)
        self.btnConnect.setObjectName("btnConnect")
        self.ip = QtWidgets.QLineEdit(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(100, 10, 113, 25))
        self.ip.setInputMask("")
        self.ip.setObjectName("ip")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(100, 40, 113, 25))
        self.login.setInputMask("")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(100, 70, 113, 25))
        self.password.setInputMask("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_ip = QtWidgets.QLabel(self.centralwidget)
        self.label_ip.setGeometry(QtCore.QRect(70, 10, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ip.setFont(font)
        self.label_ip.setObjectName("label_ip")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(50, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.label_pass = QtWidgets.QLabel(self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(20, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_pass.setFont(font)
        self.label_pass.setObjectName("label_pass")
        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(220, 10, 41, 25))
        self.port.setInputMask("")
        self.port.setAlignment(QtCore.Qt.AlignCenter)
        self.port.setObjectName("port")
        self.remember = QtWidgets.QCheckBox(self.centralwidget)
        self.remember.setGeometry(QtCore.QRect(80, 100, 161, 23))
        self.remember.setObjectName("remember")
        self.remember.setChecked(True)
        ConnectWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConnectWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectWindow)

    def retranslateUi(self, ConnectWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectWindow.setWindowTitle(
            _translate("ConnectWindow", "OpenVPN Util"))
        self.btnConnect.setText(_translate("ConnectWindow", "Connect"))
        self.login.setText(_translate("ConnectWindow", "root"))
        self.label_ip.setText(_translate("ConnectWindow", "IP:"))
        self.label_login.setText(_translate("ConnectWindow", "Login:"))
        self.label_pass.setText(_translate("ConnectWindow", "Password:"))
        self.port.setText(_translate("ConnectWindow", "22"))
        self.remember.setText(_translate(
            "ConnectWindow", "Remember connection"))


# --- Main Design ---
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 396)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serverList = QtWidgets.QListWidget(self.centralwidget)
        self.serverList.setGeometry(QtCore.QRect(20, 40, 261, 192))
        self.serverList.setSelectionMode(
            QtWidgets.QAbstractItemView.ExtendedSelection)
        self.serverList.setObjectName("serverList")
        self.fromserverLabel = QtWidgets.QLabel(self.centralwidget)
        self.fromserverLabel.setGeometry(QtCore.QRect(80, 10, 151, 21))
        self.fromserverLabel.setObjectName("fromserverLabel")
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setGeometry(QtCore.QRect(440, 240, 121, 31))
        self.importButton.setObjectName("importButton")
        self.importList = QtWidgets.QListWidget(self.centralwidget)
        self.importList.setGeometry(QtCore.QRect(300, 40, 261, 192))
        self.importList.setSelectionMode(
            QtWidgets.QAbstractItemView.ExtendedSelection)
        self.importList.setObjectName("importList")
        item = QtWidgets.QListWidgetItem()
        self.importList.addItem(item)
        self.fromfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fromfileLabel.setGeometry(QtCore.QRect(370, 10, 131, 21))
        self.fromfileLabel.setObjectName("fromfileLabel")
        self.dwnimpButton = QtWidgets.QPushButton(self.centralwidget)
        self.dwnimpButton.setEnabled(False)
        self.dwnimpButton.setGeometry(QtCore.QRect(300, 240, 121, 31))
        self.dwnimpButton.setObjectName("dwnimpButton")
        self.dwnservButton = QtWidgets.QPushButton(self.centralwidget)
        self.dwnservButton.setGeometry(QtCore.QRect(20, 240, 121, 31))
        self.dwnservButton.setObjectName("dwnservButton")
        self.revokeButton = QtWidgets.QPushButton(self.centralwidget)
        self.revokeButton.setGeometry(QtCore.QRect(160, 240, 121, 31))
        self.revokeButton.setObjectName("revokeButton")
        self.connectedText = QtWidgets.QLabel(self.centralwidget)
        self.connectedText.setGeometry(QtCore.QRect(20, 290, 91, 21))
        self.connectedText.setObjectName("connectedText")
        self.connLabel = QtWidgets.QLabel(self.centralwidget)
        self.connLabel.setGeometry(QtCore.QRect(110, 290, 91, 21))
        self.connLabel.setObjectName("connLabel")
        self.tunText = QtWidgets.QLabel(self.centralwidget)
        self.tunText.setGeometry(QtCore.QRect(20, 310, 111, 21))
        self.tunText.setObjectName("tunText")
        self.tunLabel = QtWidgets.QLabel(self.centralwidget)
        self.tunLabel.setGeometry(QtCore.QRect(130, 310, 111, 21))
        self.tunLabel.setObjectName("tunLabel")
        self.tunText_3 = QtWidgets.QLabel(self.centralwidget)
        self.tunText_3.setGeometry(QtCore.QRect(20, 330, 111, 21))
        self.tunText_3.setObjectName("tunText_3")
        self.verLabel = QtWidgets.QLabel(self.centralwidget)
        self.verLabel.setGeometry(QtCore.QRect(130, 330, 61, 21))
        self.verLabel.setObjectName("verLabel")
        self.tunText_4 = QtWidgets.QLabel(self.centralwidget)
        self.tunText_4.setGeometry(QtCore.QRect(20, 350, 131, 21))
        self.tunText_4.setObjectName("tunText_4")
        self.usersLabel = QtWidgets.QLabel(self.centralwidget)
        self.usersLabel.setGeometry(QtCore.QRect(150, 350, 61, 21))
        self.usersLabel.setObjectName("usersLabel")
        self.importButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.importButton_2.setGeometry(QtCore.QRect(440, 280, 121, 31))
        self.importButton_2.setObjectName("importButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenVPN Assitant"))
        self.fromserverLabel.setText(_translate(
            "MainWindow", "Select user(s) from server:"))
        self.importButton.setText(_translate("MainWindow", "Import from file"))
        __sortingEnabled = self.importList.isSortingEnabled()
        self.importList.setSortingEnabled(False)
        item = self.importList.item(0)
        item.setText(_translate("MainWindow", "Import users from file"))
        self.importList.setSortingEnabled(__sortingEnabled)
        self.fromfileLabel.setText(_translate(
            "MainWindow", "Select user(s) from file:"))
        self.dwnimpButton.setText(_translate(
            "MainWindow", "Download imported"))
        self.dwnservButton.setText(_translate(
            "MainWindow", "Download Selected"))
        self.revokeButton.setText(_translate("MainWindow", "Revoke Selected"))
        self.connectedText.setText(_translate("MainWindow", "Connected to:"))
        self.connLabel.setText(_translate("MainWindow", "error"))
        self.tunText.setText(_translate("MainWindow", "Current tunnel IP:"))
        self.tunLabel.setText(_translate("MainWindow", "error"))
        self.tunText_3.setText(_translate("MainWindow", "OpenVPN version:"))
        self.verLabel.setText(_translate("MainWindow", "error"))
        self.tunText_4.setText(_translate(
            "MainWindow", "Total users on server:"))
        self.usersLabel.setText(_translate("MainWindow", "error"))
        self.importButton_2.setText(_translate(
            "MainWindow", "Edit server config"))
